//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
<<<<<<< HEAD
//     运行时版本:4.0.30319.1026
=======
//     运行时版本:4.0.30319.42000
>>>>>>> 7c57701bb9f59cd6631acfbeb322f9d04584b178
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
<<<<<<< HEAD
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
=======
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
>>>>>>> 7c57701bb9f59cd6631acfbeb322f9d04584b178
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PC-201211211604;Initial Catalog=bookmanage;User ID=sa;Password=sa")]
        public string bookmanageConnectionString {
            get {
                return ((string)(this["bookmanageConnectionString"]));
            }
        }
<<<<<<< HEAD
=======
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=bookmanage;Persist Security Info=True;User " +
            "ID=sa;Password=sa")]
        public string bookmanageConnectionSchbk {
            get {
                return ((string)(this["bookmanageConnectionSchbk"]));
            }
        }
>>>>>>> 7c57701bb9f59cd6631acfbeb322f9d04584b178
    }
}
